package vn.elca.training.repository;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.transaction.annotation.Transactional;
import vn.elca.training.ApplicationWebConfig;
import vn.elca.training.model.entity.Employee;
import vn.elca.training.model.entity.Group;
import vn.elca.training.model.entity.Project;
import vn.elca.training.testutil.TestEntityFactory;

import java.time.LocalDate;
import java.util.Optional;
import org.junit.Assert;

import static org.assertj.core.api.Assertions.assertThat;


@ContextConfiguration(classes = {ApplicationWebConfig.class})
@RunWith(value= SpringRunner.class)
public class GroupRepositoryTest {
    @Autowired
    private GroupRepository groupRepository;

    @Autowired
    private ProjectRepository projectRepository;

    @Test
    @Transactional
    @Rollback(true)
    public void shouldSaveAndFindGroupById() {
        Employee leader = new Employee(
                "ABC",
                "John",
                "Doe",
                LocalDate.of(1995, 1, 1)
        );

        Group group = new Group();
        group.setLeader(leader);

        Group savedGroup = groupRepository.save(group);

        Optional<Group> foundGroup = groupRepository.findById(savedGroup.getId());

        assertThat(foundGroup).isPresent();
        assertThat(foundGroup.get().getId()).isEqualTo(savedGroup.getId());
        assertThat(foundGroup.get().getLeader()).isNotNull();
        assertThat(foundGroup.get().getLeader().getId()).isEqualTo(leader.getId());
    }

    @Test
    @Transactional
    @Rollback(true)
    public void shouldCountSavedGroups() {
        long initialGroupCount = groupRepository.count();

        Employee countLeader = new Employee(
                "CNT",
                "Count",
                "Leader",
                LocalDate.of(1990, 2, 2)
        );
        Group countGroup = new Group();
        countGroup.setLeader(countLeader);
        groupRepository.save(countGroup);

        Assert.assertEquals(initialGroupCount + 1, groupRepository.count());
    }

    @Test
    @Transactional
    @Rollback(true)
    public void shouldPersistLeaderWhenSavingGroup() {
        Employee leader = new Employee(
                "LDR",
                "Linda",
                "Leader",
                LocalDate.of(1988, 3, 3)
        );

        Group group = new Group();
        group.setLeader(leader);
        Group savedGroup = groupRepository.save(group);

        Assert.assertNotNull("Group id should be generated", savedGroup.getId());
        Assert.assertNotNull("Leader id should be generated by cascade persist", savedGroup.getLeader().getId());
        Assert.assertEquals("LDR", savedGroup.getLeader().getVisa());
        Assert.assertEquals("Linda", savedGroup.getLeader().getFirstName());
    }

    @Test
    @Transactional
    @Rollback(true)
    public void shouldPersistProjectsWhenSavingGroup() {
        Group group = new Group();
        group.setLeader(new Employee(
                "GRP",
                "Grace",
                "GroupLeader",
                LocalDate.of(1985, 4, 4)
        ));

        Project project = TestEntityFactory.project(
                "GROUP_REPOSITORY_PROJECT",
                LocalDate.of(2026, 12, 31),
                "GROUP_REPOSITORY_CUSTOMER"
        );
        project.setGroup(group);
        group.getProjects().add(project);

        Group savedGroup = groupRepository.save(group);

        Assert.assertNotNull("Project id should be generated by cascade persist", project.getId());

        Project foundProject = projectRepository.findById(project.getId()).orElse(null);
        Assert.assertNotNull("Project should be found after saving group", foundProject);
        Assert.assertNotNull("Project group should be set", foundProject.getGroup());
        Assert.assertEquals(savedGroup.getId(), foundProject.getGroup().getId());
        Assert.assertEquals("GRP", foundProject.getGroup().getLeader().getVisa());
    }

    @Test
    @Transactional
    @Rollback(true)
    public void shouldDeleteGroupById() {
        Group deleteGroup = new Group();
        deleteGroup.setLeader(new Employee(
                "DEL",
                "Delete",
                "Leader",
                LocalDate.of(1991, 5, 5)
        ));
        Group savedGroup = groupRepository.save(deleteGroup);

        Long groupId = savedGroup.getId();

        Assert.assertTrue("Group should exist before deletion", groupRepository.existsById(groupId));

        groupRepository.deleteById(groupId);

        Assert.assertFalse("Group should not exist after deletion", groupRepository.existsById(groupId));
    }
}
